version: '3.8'
services:
  rctf:
    build: .
    restart: always
    ports:
      - '8080:4000'
    environment:
      - API_URL=http://host.docker.internal:3000
    env_file:
      - .env
    volumes:
      - ./conf.d:/app/conf.d
