version: "3.8"
name: telos-dev
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-ext-telos.toml:/traefik-ext-telos.toml
    command:
      - --entrypoints.web.address=:80
      - --providers.file.filename=/traefik-ext-telos.toml
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --api.insecure=true

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.traefik.me`) && PathPrefix(`/api`, `/dashboard`)
      - traefik.http.routers.traefik.service=api@internal

    ports:
      - 8080:80
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  default:
    name: traefik
