[http.routers]
  [http.routers.dctf]
    entryPoints = ["web"]
    rule = "Host(`dctf.traefik.me`)"
    service = "dctf-ext-srv"
[[http.services.dctf-ext-srv.loadBalancer.servers]]
  url = "http://host.docker.internal:4000"

  