[http.routers]
  [http.routers.telos]
    entryPoints = ["web"]
    rule = "Host(`telos.traefik.me`)"
    service = "telos-ext-srv"
[[http.services.telos-ext-srv.loadBalancer.servers]]
  url = "http://host.docker.internal:4000"

  